quarkus:
  datasource:
    jdbc:
      url: jdbc:postgresql://localhost:5432/mydb
      driver: org.postgresql.Driver
    db-kind: postgresql
    username: van_der_weiss
    password: 123123123
  hibernate-orm:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    database:
      generation: create
"%test":
   quarkus:
     datasource:
       jdbc:
         url: jdbc:h2:mem:testdb
         driver: org.h2.Driver
       db-kind: h2
       username: sa
       password: password
     hibernate-orm:
       sql-load-script: "import.sql"
       dialect: org.hibernate.dialect.H2Dialect
       database:
         generation: drop-and-create
